[paths]
linux   = "/media/almacen/deml/Downloads/core_instruction"
windows = "D:\\Downloads\\core_instruction"

[wiki]
subfolder = "wiki"

[scratchpad]
subfolder = "wiki/scratchpad.md"
images    = "scratchpad/images"
